### ISSUE TITLE
Crash "Out of memory" after CTRL+P, cannot save files as pdf

### ISSUE THREAD

**Issue by ImWinningPowa** [isanchop/stuhack#17]
As the title says, I cannot save the files as pdf after opening them on the page after clicking on download.
The page opens, continues in an endless loading and then crashes in "out of memory" error page, I have tried on different computers but get the same result.
The problem that was present in 0.4.6 that only displayed the first page has disappeared.
Excellent work, keep going!

**Comment by ImWinningPowa** [comment]
As you said, I did some tests and confirmed what you supposed a few days ago, files containing more than 50 pages cause the print page to crash from this version of chrome.
I have also tried with smaller files (up to 40 pages) and there is no problem.
The solution of being able to split the file into several parts and then merge them with some external software seems to be the most appropriate for this type of problem
Hope you'll be able to find a solution!

**Comment by isanchop** [comment]
Well, you were actually right too, before it was performing better, but because of updates from the Studocu team trying to make this project obsolete and fix the previous errors, in the past release I added some CSS transformations in order to make the add on work. This requires much more computation, and that's what you have noticed as "Crash out of memory". I think there might be a way to optimize the processing when downloading, but I still have to figure it out.
I am just a student trying to help out a bit with this project, but I have many other things right now (final exams...😮‍💨) and not getting any incentives from this project except your support, which is why I have been updating this plugin.
So give me a couple of weeks to catch up on university work, and I will focus on this project again 😉.

**Comment by TheArmKing** [comment]
@ImWinningPowa could you try my fork (https://github.com/TheArmKing/stuhack) and see if it helps? You can adjust the `PAGES_PER_WINDOW` in the `doc-viewer.js` file. It will split the file and open multiple windows with pages of the given amount at once. (Currently: 50 pages per window). You can then save the contents of each window separately and combine them using some other software.

**Comment by ImWinningPowa** [comment]
@TheArmKing It's a fantastic work, it still takes a while to print but it is a great temporary solution.
Good job

**Comment by TheArmKing** [comment]
@ImWinningPowa Oh that's great. If you want to adjust the limit, all you have to do is edit the `doc-viewer.js` file on disk and reload the extension (and any open StuDocu tabs) in `chrome://extensions`. What I have noticed is documents that are more text-based take longer. For such documents, `PAGES_PER_WINDOW = 20;` works quite well on my machine.

**Comment by isanchop** [comment]
seems like google chrome already fixed something and works just fine now with no need of transformations. So you will be able to download the docs much faster and any number of pages. 
Just try (version 0.4.8)[https://github.com/isanchop/stuhack/releases/tag/v0.4.8] and tell me if it is working now for you.
:)

**Comment by ImWinningPowa** [comment]
@isanchop Well done, that's a great fix! Have a good holyday!
