### ISSUE TITLE
File Content

### ISSUE THREAD

**Issue by nolnolisnolnol** [isanchop/stuhack#33]
whenever i save a file then checking it, i noticed some unnnecessary stuff on every page like the text content at the bottom page got cropped and the text content from the next page got included 
[8 In class Tutorial Questions &amp; Solutions Business Combinations &amp; Consolidations.pdf](https://github.com/isanchop/stuhack/files/12706283/8.In.class.Tutorial.Questions.amp.Solutions.Business.Combinations.amp.Consolidations.pdf)
see file for more understanding thanks admin

**Comment by isanchop** [comment]
Hey! Thanks for your comment.
You are getting some cropped elements of your document due to your settings when saving the PDF.
Before saving, make sure your settings look something like the following:
<img width="1000" alt="image" src="https://github.com/isanchop/stuhack/assets/67743899/74ee9792-bb12-4275-a36e-325a560444cb">

You can play around with those and get a preview on the left of how the document is going to look.
Here you have the same document with these settings:
[8 In-class Tutorial Questions & Solutions Business Combinations & Consolidations.pdf](https://github.com/isanchop/stuhack/files/12707022/8.In.class.Tutorial.Questions.amp.Solutions.Business.Combinations.amp.Consolidations.pdf)
Hope this will help you :)

**Comment by nolnolisnolnol** [comment]
> Hey! Thanks for your comment. You are getting some cropped elements of your document due to your settings when saving the PDF. Before saving, make sure your settings look something like the following: <img alt="image" width="1000" src="https://user-images.githubusercontent.com/67743899/270124126-74ee9792-bb12-4275-a36e-325a560444cb.png">
> 
> You can play around with those and get a preview on the left of how the document is going to look. Here you have the same document with these settings: [8 In-class Tutorial Questions & Solutions Business Combinations & Consolidations.pdf](https://github.com/isanchop/stuhack/files/12707022/8.In.class.Tutorial.Questions.amp.Solutions.Business.Combinations.amp.Consolidations.pdf) Hope this will help you :)
