### ISSUE TITLE
Manifest file error

### ISSUE THREAD

**Issue by Gaunhoishit** [isanchop/stuhack#8]
Hello! Thanks for your work.
But I have a problem, when I add the extension to chrome there is an error about manifest and it doesn't work. It says "Manifest version 2 is deprecated, and support will be removed in 2023." 
Is there anything you can do about this?

**Comment by isanchop** [comment]
Hey, yeah it is a super easy fix you can just go to the "manifest.json" and change it's version from 2 to 3 (it is te first line of code). I will just leave it with version 2 by now because for the moment works just fine and when I checked to make the chrome extension for safari it was not compatible with version 3 at that moment. 
But any way version 2 should be working all right.
Thanks for your reply, if you ave any other issues do not hesitate to ask them.  ;)
